# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'omni-parser-app'
primary_region = 'sin'

[build]
  image = "python:latest"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 4
